title: Tools for Computer Science
description: Sammlung von Tipps und nützlichen Ressourcen für Informatik Erstsemester
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - ckurs.md
  - linux.md
  - windows.md
  - macos.md
  - head.html
theme: jekyll-theme-cayman
